# Generated by Django 3.0.2 on 2022-06-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='first_registration',
            field=models.BooleanField(default=True),
        ),
    ]
