# Generated by Django 3.0.2 on 2022-06-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0004_candidate_current_working'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='country_code',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone_number',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
