# Generated by Django 3.0.2 on 2022-06-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0008_auto_20220625_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='seek_backend/static/candidateFiles'),
        ),
    ]
