# Generated by Django 3.0.2 on 2022-05-28 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobsearchbars', '0002_jobclassifications_joblocations'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264)),
                ('desciption', models.TextField(max_length=10000)),
                ('jobclassification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='jobsearchbars.jobclassifications')),
                ('joblocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='jobsearchbars.joblocations')),
            ],
        ),
    ]
